
//
/* PLOP_INJECT_IMPORT */

import 'intl-pluralrules';
import i18next from 'i18next';

/**
 * AppStrings
 * est une bibliothèque de strings multilingues
 *
 * il faut initialiser cette bibliothèque dans App.js,
 * avec la fonction d'init
 *
 */

// les strings selon pays
const translations = {
  en: {
    translation: {
      /* PLOP_INJECT_SRC_STRING */
      "xkpEDQ8t": "Failed to install hex on Arduino UNO:",
      "xYJkIqwm": "New instance cannot be created!!",
      "xO7ZBv8": "No access to camera",
      "xFjUd1xH": "File Saved to gallery!",
      "xHCVPMcX": "No QR code to download.",
      "xesK1QSp": "Cloud save failed homie..... Try again soldier",
      "xjJQt4i": "google login cancelled",
      "xCRZALjm": "google/fb login error:",
      "x3HAGIz": "one or more database cloud saves failed",
      "xOMFA69Q": "google/fb login error:",
      "xZL6EBId": "google login cancelled",
      "xvFbSiUM": "one or more database cloud saves failed",
      "xGmtzh7t": "Do you want to delete this work?",
      "x0vdnKW5": "Some work is already going on, brother!",
      "xWQ2YEPr": "Do you want to delete this work?",
      "xb9dUQ9T": "Some work is already going on, my dear brother!",
      "xc3lKws4": "Permission Denied! You need to give storage permission to download the file",
      "xtJmvMj6": "Deletion successful!! :",
      "xPRoIUP": "New instance cannot be created!",
      "x8dg9LRr": "Login successful! But.... This account doesn't exist!",
      "xGURyoWg": "Login successful!",
      "xgpEDcQ5": "Login stopped ;-)",
      "xMhxIbI3": "Login failed... Try again ;-)",
      "xko6nGyO": "Logout failed... Try again ;-)",
      "x6lEqMKs": "Logout successful!",
      "xfnALXBd": "Blue pill, Red pill? Choose a pill as you please.",
      "xNPv7aa": "Blue pill, Red pill? Choose a pill as you please.",
      "xlCyp2sY": "Option 2",
      "xmQbIBwM": "Option 1",
      "xoG44AdY": "Blue pill, Red pill? Choose a pill as you please.",
      "xRDM5lr2": "Blue pill, Red pill? Choose a pill if you please.",
      "xL6HQGEv": "Option 2",
      "xyyaUqVV": "Option 1",
      "xpsVRjmW": "This program doesn't exist:",
      "xcnEx3W6": "Let's install this program!",
      "x4WAaDXQ": "Blue pill, Red pill? Choose a pill if you please.",
      "xviDPW0S": "Pikachu skiing.",
      "xwQ4S6Y0": "Let's get started ;-)",
      "xh63gX8x": "Invalid status",
      "xu0ZLfgj": "Invalid status",
      "xrcruDA": "Oopsie, there's a problem, try again ;-)",
      "x8RvoQIj": "The compilation is successful! Now it's time for you to use the companion app called ArduinoGPTHex, available for Android (Windows/Linux/MacOS coming soon) to install this compiled program on your Arduino device.",
      "xc8HGDn3": "Please wait... The compilation is taking place right now ;-)",
      "xhByF48m": "Press the button above to compile and then install this great program on your Arduino device, via USB, and the ArduinoGPTHex app, available for Android (Windows/Linux/MacOS coming soon)",
      "xrLtiCEC": "Write the description here",
      "xOvgDUJs": "Do you want to make this program public, or private?",
      "xCPbZbuc": "In the next step, add {{VARIABLE_NAME}} placeholders in your code, so that the user of your program can provide data to your program. More details in the next step.",
      "xaGwix91": "Press this button to download this QR Code. Scanning this code with the QR scanner of this app redirects the user/you to the desired program installation page.",
      "xBO7xp7z": "A string",
      "xQiatCVw": "A number",
      "xFqmGyxK": "What is the type of this user variable?",
      "xGaHOwl": "Write a sentence that will explain to the user what this value is needed for",
      "xQ17u4C4": "Your program doesn't need user data to work, so you can go to the next step.",
      "xSBqRz": "Click each user variable and add the required info.",
      "x4ieqQnw": "Pikachu skiing.",
      "xb7qyY1z": "Invalid status",
      "xhslrJw8": "Invalid status",
      "xpXCPPzc": "An error occurred while loading the data ;-)",
      "xUU2wpQN": "Data loading successful!",
      "x0hEujDe": "Please wait while data is loading ;-)",
      "xdOmeGv": "Press the button above to create a complete tutorial, thanks to all the efforts you have made so far... I am proud of you ;-)",
      "x9nmlFx8": "Type the description here",
      "xYDRDZXj": "Pikachu skiing.",
      "xqcQT8Ya": "Type the description here",
      "xPPeViLE": "Invalid status",
      "xK4KI2gw": "Invalid status",
      "x7bW6GWv": "There was an issue during the work... Try again ;-)",
      "xN73VeXp": "Work done successfully!",
      "xDqWJPrB": "Please wait while the work is being done ;-)",
      "xcfEBXL": "Press the button above to create an Arduino program from your description.",
      "xOLGJe39": "Your Arduino program will be here soon",
      "xuMzbhB": "Pikachu skiing.",
      "xicECXV": "Let's get started!",
      "xRAOuMnR": "Invalid status",
      "xVK1MBV": "Invalid status",
      "x6n7Ke9E": "Oopsie, there's a problem, try again ;-)",
      "xIq3ugH8": "The compilation is successful! Now it's time for you to use the companion app called ArduinoGPTHex, available for Android (Windows/Linux/MacOS coming soon) to install this compiled program on your Arduino device.",
      "xOoCK7ft": "Please wait... The compilation is taking place right now ;-)",
      "xtMZuUn": "Press the button above to compile and then install this great program on your Arduino device, via USB, and the ArduinoGPTHex app, available for Android (Windows/Linux/MacOS coming soon)",
      "xYZg1si7": "Write the description here",
      "xSUtH3qA": "Pikachu skiing.",
      "xjTaydry": "Invalid status",
      "xX3dnrcb": "Invalid status",
      "x50qE8X": "An error occurred while loading the data ;-)",
      "xBCHPzI4": "Data loading successful!",
      "xqwYRy0B": "Please wait while the data is loading ;-)",
      "x9fPcK9b": "Press the button above to create a complete tutorial, thanks to all the efforts you have made so far... I am proud of you ;-)",
      "xzq5IFoV": "Type your code here",
      "xchAxP9H": "Blue pill, Red pill? Choose a pill, please.",
      "xhXpDKpi": "Option 2",
      "xlGywq7S": "Option 1",
      "x1KVUz3U": "Cannot create a new instance of PlayerGTA.",
      "xyjJ1GaA": "This button is useless",
      "xsQxpbdW": "Add some choices, dude, in your program",
      "xdTbnvWd": "The button below makes noise.",
      "xSoZVodD": "This button is useless",
      "xPgSenoH": "Add some questions, dude, in your program",
      "xPuScS2M": "Black n' Yellow/Orange",
      "APIScreenMsg": "Use the button below to subscribe to the API, or to buy API Credits, or to get info about your API Subscription, then enter your API Key in the prompt, and finally, press the prompt button.",
      "EnterAPIKeyHere": "Enter your API Key here",
      "APIButtonText": "The powerful API button!",
      "SubAPIMsg": "Subscribe to the API",
      "Buy5KMsg": "Buy 5000 API Credits",
      "GetFreshAPIInfo": "Press this button to get your freshest API info",
      "LemonButton": "Press me",
      "LoginError": "There was a problem during the login.",
      "LoginCancel": "Login canceled",
      "Success": "Success",
      "Error": "Error",
      "GetToolboxChoice": "What do you want to do?",
      "APIKeySuccess": "API Key given successfully!",
      "APICreditsError": "We couldn't generate an API Credits checkout link for you.... Try again, soldier!",
      "LetsBuyAPICredits": "Let's go to the API Credits checkout page!",
      "APISubError": "We couldn't generate an API subscription link for you.... Try again, soldier!",
      "LetsAPISub": "Let's go to the API subscription page!",
      "asyncWorkSuccess": "The asynchronous work completed successfully ;-)",
      "asyncWorkStarted": "The asynchronous work just started ;-)",
      "xxE6QqH": "Oops.... This value is not valid.",
      "xzsHU3nz": "Oops.... This value is not valid.",
      "xcnejw3": "Oops.... This value is not valid.",
      "xQ10ZTQ7": "Oops.... This value is not valid.",
      "xQkzkkqT": "Oops.... This value is not valid.",
      "x0EtNET": "Test error",
      "Login": "Login (Google)",
      "Logout": "Logout (Google)",
      "xJ9h8fL1": "set checkInput to true",
      "xOlvmwdF": "Oops... Try again",
      "xpz3vNzy": "Scanner",
      "xiTubVs": "set checkInput to true, buddy",
      "xC79vQ4Y": "Write the user variable here.",
      "xsYAZEbo": "This value is not valid",
      "xKWRoJ4M": "Installer",
      "x2l42K1l": "All Programs",
      "xXGgUH": "Check your Internet and try again !",
      "xnlAqvHs": "Try again",
      "xCrCn6QI": "That's not needed",
      "xC5rai2k": "That's not needed",
      "xD6MtqGT": "Choose your program's public availability",
      "xpKkWfEJ": "set checkInput to true",
      "xNSU9RWl": "There must be some code, your code editor seems to be empty. write some code, please.",
      "xS5p7J": "set checkInput to true so this disappears",
      "xEo8VION": "There's no compiled code available... Press the compilation button above.",
      "xlEu9A5o": "This API key is not valid. Please enter a valid API key.",
      "xbfB9hke": "API Key",
      "AddAPIKey": "Add an API key, buddy",
      "xVKu2Q1c": "It seems like there's no Arduino program generated... Press the creation button above.",
      "xM97hie": "You need to write a description of your Arduino program, otherwise, how are we supposed to create something for you ? ;-)",
      "xsdnHZwr": "Describe your Arduino program in the next step. This description will then be translated into Arduino program with the help of artificial intelligence.",
      "xwZa27Mn": "This UI doesn't need error messages since it doesn't get data from the user. Remember to set checkInput of this UI to true.",
      "x7pT5Y7": "My Programs",
      "xVpJlYl": "Press the button below to create an Arduino program",
      "xAifNH1h": "New Program",
      "xQCoxcFX": "Give a name to your Arduino program. For example, 'The LED-Powered XMAS tree made by DIYMaster434'",
      "xIiRxOK0": "This program name is not valid",
      "x0qpHyto": "The cloud data restore failed! Try again, soldier!",
      "xSpTMl1n": "Your data is now locally restored, from the cloud!",
      "xAmgHBho": "The cloud save failed! Try again, soldier!",
      "xNUgKxo": "Your data is now safe in the cloud!",
      "xK6jy8ax": "Write the name of this thing, adventurer!",
      "xdBhrfN": "Oops... This value is not valid.",
      "xBlM1Zi": "Title",
      "xriErHWm": "This page is empty! Please fill me up.",
      "xE8cpvzD": "Fill me up!",
      "pressToDelete": "Press the button to remove this item from your list",
      "ZeFokinToolz": "The Tools",
      "Add": "Add",
      "Edit": "Edit",
      "cancel": "Cancel",
      "country": "en",
      "typeHere": "Type here",
      "doWeDelete": "Do you really want to delete this item?",
      "poubelle": "Heading to the cosmic trash bin.",
      "DOB": "Date of birth",
      "OK": "OK",
      "TypeSomePlz": "Please type something.",
      "TypeBabyName": "Give him a name.",
      "askExtStoragePerm": "The app needs permission to store data on your device. Do you accept?",
      "question": "What do you want to do?",
      "plzWait": "Please wait.",
      "annuler": "Cancel",
      "non": "No",
      "oui": "Yes",
      "besoinsDeBase": "Basic Needs",
      "besoinsSpirituels": "Spiritual Needs",
      "besoinsTerritoriaux": "Territorial Needs",
      "chooseCategory": "Which category of Maslow's Pyramid does your tutorial fall under?",
      "Toolbox": "Tools",
      "NoTools": "No tools available",
      "AddTool": "Add a tool",
      "WrongTool": "This tool is crap",
      "SaveDBCloud": "Save your user data in the cloud",
      "BackupDBCloud": "Recover your user data, stored in the cloud"

      /* PLOP_INJECT_SRC_END */
    },
  },
  /* PLOP_INJECT_INTL_STRINGS */

};

function InitAppStrings() {
  //const i18nApp2 = i18next.createInstance();

  i18next.init({
    fallbackLng: 'en',
    resources: translations,
  });

  return i18next;
}

const app_strings = InitAppStrings();

export { InitAppStrings, app_strings };
